# Generated by Django 5.0.3 on 2024-04-26 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrder', '0002_alter_orderitem_food_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='food',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
