# Generated by Django 5.0.3 on 2024-04-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appOrder', '0006_orderfood_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appOrder.payment'),
        ),
        migrations.DeleteModel(
            name='OrderFood',
        ),
    ]
