# Generated by Django 5.0.3 on 2024-04-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrder', '0007_remove_order_is_ordered_order_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
