# Generated by Django 5.0.3 on 2024-05-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrder', '0009_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
