# Generated by Django 5.0.3 on 2024-05-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOrder', '0010_remove_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
