# Generated by Django 5.0.3 on 2024-04-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
