# Generated by Django 5.0.3 on 2024-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=40, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, max_length=200)),
                ('category_image', models.ImageField(upload_to='photos/category')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='food',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
