# Generated by Django 5.0.3 on 2024-04-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appStore', '0007_alter_food_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
